# Generated by Django 3.2 on 2021-04-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_id', models.CharField(max_length=20, unique=True, verbose_name='financemarker ID')),
                ('exchange', models.CharField(max_length=20, verbose_name='Биржа')),
                ('full_exchange', models.CharField(max_length=40, verbose_name='Биржа полное название')),
                ('transaction_type', models.CharField(max_length=2, verbose_name='Тип транзакции')),
                ('code', models.CharField(max_length=10, verbose_name='Тикер компании')),
                ('owner', models.CharField(max_length=20, verbose_name='Название компании')),
                ('transaction_date', models.DateField(verbose_name='Дата транзакции')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('amount', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('value', models.FloatField(verbose_name='Cумма сделки')),
                ('trades_curr', models.CharField(max_length=5, verbose_name='Валюта')),
            ],
        ),
    ]
