# Generated by Django 3.2 on 2021-04-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Тикер компании')),
                ('name', models.CharField(max_length=20, verbose_name='Название компании')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('full_name', models.CharField(max_length=40, unique=True, verbose_name='Полное название')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, verbose_name='id telegram пользователя')),
                ('message_id', models.CharField(max_length=40, verbose_name='id telegram сообщения')),
            ],
        ),
        migrations.CreateModel(
            name='TelegraphAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, verbose_name='Короткое имя')),
                ('author_name', models.CharField(max_length=20, verbose_name='Имя автора')),
                ('author_url', models.CharField(max_length=40, null=True, verbose_name='Ссылка на автора')),
                ('access_token', models.CharField(max_length=60, verbose_name='Токен аккаунта')),
                ('auth_url', models.CharField(max_length=60, null=True, verbose_name='Url авторизации')),
            ],
            options={
                'verbose_name': 'Аккаунт Telegraph',
                'verbose_name_plural': 'Аккаунты Telegraph',
            },
        ),
        migrations.CreateModel(
            name='TelegraphPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=40, verbose_name='Путь')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.telegraphaccount', verbose_name='Аккаунт')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.company', unique=True, verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Страницa Telegraph',
                'verbose_name_plural': 'Страницы Telegraph',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_id', models.CharField(max_length=30, unique=True, verbose_name='financemarker ID')),
                ('title', models.CharField(max_length=20, null=True, verbose_name='Заголовок')),
                ('content', models.TextField(null=True, verbose_name='Текст')),
                ('link', models.CharField(max_length=50, null=True, verbose_name='Ссылка')),
                ('publicated', models.DateTimeField(verbose_name='Время и дата публикации')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.company', verbose_name='Компания')),
                ('telegraph_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financemarker.telegraphpage', verbose_name='Страница Telegraph')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-publicated'],
            },
        ),
        migrations.CreateModel(
            name='Insider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fm_id', models.CharField(max_length=30, unique=True, verbose_name='financemarker ID')),
                ('transaction_type', models.CharField(choices=[('P', 'Покупка'), ('S', 'Продажа'), ('M', 'Опцион')], max_length=2, verbose_name='Тип транзакции')),
                ('transaction_date', models.DateField(verbose_name='Дата транзакции')),
                ('name', models.CharField(max_length=20, null=True, verbose_name='Название')),
                ('amount', models.IntegerField(null=True, verbose_name='Количество')),
                ('price', models.FloatField(null=True, verbose_name='Цена')),
                ('value', models.FloatField(null=True, verbose_name='Cумма сделки')),
                ('trades_curr', models.CharField(choices=[('RUB', '₽'), ('USD', '$')], max_length=5, verbose_name='Валюта')),
                ('tg_messaged', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.company', verbose_name='Компания')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.exchange', verbose_name='Биржа')),
            ],
            options={
                'verbose_name': 'Инсайдер',
                'verbose_name_plural': 'Инсайдеры',
                'ordering': ['transaction_date'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.exchange', verbose_name='Биржа'),
        ),
    ]
