# Generated by Django 3.2 on 2021-04-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insider',
            name='transaction_type',
            field=models.CharField(choices=[('P', 'Покупка'), ('S', 'Продажа'), ('M', 'Опцион')], max_length=2, verbose_name='Тип транзакции'),
        ),
    ]
