# Generated by Django 3.2 on 2021-04-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0002_alter_insider_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insider',
            name='trades_curr',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$')], max_length=5, verbose_name='Валюта'),
        ),
    ]
