# Generated by Django 3.2 on 2021-04-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0003_alter_insider_trades_curr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insider',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Тикер компании'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='exchange',
            field=models.CharField(max_length=20, null=True, verbose_name='Биржа'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='fm_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='financemarker ID'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='full_exchange',
            field=models.CharField(max_length=40, null=True, verbose_name='Биржа полное название'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='owner',
            field=models.CharField(max_length=20, null=True, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='insider',
            name='value',
            field=models.FloatField(null=True, verbose_name='Cумма сделки'),
        ),
    ]
