# Generated by Django 3.2 on 2021-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0004_auto_20210409_1515'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insider',
            options={'verbose_name': 'Инсайдер', 'verbose_name_plural': 'Инсайдеры'},
        ),
        migrations.AddField(
            model_name='insider',
            name='parsed',
            field=models.BooleanField(default=False),
        ),
    ]
