# Generated by Django 3.2 on 2021-04-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0005_auto_20210413_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insider',
            old_name='parsed',
            new_name='tg_messaged',
        ),
    ]
