# Generated by Django 3.2 on 2021-04-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0007_newsitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegraphAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=20, verbose_name='Короткое имя')),
                ('author_name', models.CharField(max_length=20, verbose_name='Имя автора')),
                ('author_url', models.CharField(max_length=40, null=True, verbose_name='Ссылка на автора')),
                ('access_token', models.CharField(max_length=60, verbose_name='Токен аккаунта')),
                ('auth_url', models.CharField(max_length=60, null=True, verbose_name='Url авторизации')),
            ],
        ),
    ]
