# Generated by Django 3.2 on 2021-04-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financemarker', '0008_telegraphaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegraphPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=40, verbose_name='Путь')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('content', models.TextField(verbose_name='Контент')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.telegraphaccount', verbose_name='Аккаунт')),
                ('insider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.insider', verbose_name='Инсайдер')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financemarker.newsitem', verbose_name='Новость')),
            ],
        ),
    ]
